name: daftary
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.3.4
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  intl: ^0.20.1
  font_awesome_flutter: ^10.8.0
  equatable: ^2.0.7
  uuid: ^4.5.1
  instabug_flutter: ^14.1.0
  flutter_dotenv: ^5.1.0

  # Local packages
  expense_repository:
    path: packages/expense_repository
  auth_repository:
    path: packages/auth_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
