name: daftary
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.1
  font_awesome_flutter: ^10.8.0

  expense_repository:
    path: packages/expense_repository
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  firebase_core: ^3.10.1
  equatable: ^2.0.7
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
